# Generated by Django 4.0.4 on 2022-04-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bancorigem', models.CharField(max_length=150)),
                ('agenciaorigem', models.CharField(max_length=150, unique=True)),
                ('contaorigem', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('bancodestino', models.CharField(max_length=150)),
                ('agenciadestino', models.CharField(max_length=150, unique=True)),
                ('contadestino', models.CharField(max_length=150, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('datahora', models.DateTimeField(blank=True, null=True, verbose_name='data/hora')),
            ],
        ),
    ]
