# Generated by Django 4.0.4 on 2022-04-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='address',
        ),
        migrations.RemoveField(
            model_name='document',
            name='agenciadestino',
        ),
        migrations.RemoveField(
            model_name='document',
            name='agenciaorigem',
        ),
        migrations.RemoveField(
            model_name='document',
            name='bancodestino',
        ),
        migrations.RemoveField(
            model_name='document',
            name='bancorigem',
        ),
        migrations.RemoveField(
            model_name='document',
            name='contadestino',
        ),
        migrations.RemoveField(
            model_name='document',
            name='contaorigem',
        ),
        migrations.RemoveField(
            model_name='document',
            name='datahora',
        ),
        migrations.RemoveField(
            model_name='document',
            name='valor',
        ),
    ]
